### ISSUE TITLE
the footer hides the last content, I already scroll to the bottom

### ISSUE THREAD

**Issue by flora8984461** [pdc-uottawa/PDCwebsite#27]
![image](https://user-images.githubusercontent.com/39588094/90986872-37899b00-e554-11ea-964d-c8b4357a63a4.png)
![image](https://user-images.githubusercontent.com/39588094/90986873-3bb5b880-e554-11ea-9891-00109feaa4a0.png)

**Comment by navpreetkaur051** [comment]
Fixed, need to test again and then close

**Comment by sunakshi95** [comment]
It has been tested and ready for deployment.
