### ISSUE TITLE
Registration form changes

### ISSUE THREAD

**Issue by navpreetkaur051** [pdc-uottawa/PDCwebsite#38]
use shorter labels.
Drop down for program names.

**Comment by navpreetkaur051** [comment]
Profile maintenance. 
give linkedin profile url option.

**Comment by HarmanBhutani** [comment]
Linkedin text box added , Course drop down menu updated !

**Comment by HarmanBhutani** [comment]
Registration form completed
https://github.com/pdc-uottawa/PDCwebsite/commit/dceb9da3e86b6b3ce46bc3ced48f3378d722bb67

**Comment by navpreetkaur051** [comment]
This seems incomplete.
Close after Sunakshi tests it.

**Comment by sunakshi95** [comment]
Tested. Ready for deployment.
