### ISSUE TITLE
Filter 3 projects.

### ISSUE THREAD

**Issue by navpreetkaur051** [pdc-uottawa/PDCwebsite#40]
create 3 projects
1- initiated by pdc
other by city
3rd one be like canbewell.
Have these 3 on the website.
---logo
---intro of industry partner
---name of the industry partner in hosted by.

**Comment by navpreetkaur051** [comment]
Point of contact field on project dashboard page.

**Comment by navpreetkaur051** [comment]
Project list refining. #33

**Comment by HarmanBhutani** [comment]
tested and working fine.
