### ISSUE TITLE
Event brite api changes

### ISSUE THREAD

**Issue by navpreetkaur051** [pdc-uottawa/PDCwebsite#45]
Hi,     
We’re writing to inform you     that we will be making a breaking change to our API related to our Event     object and the way we handle event descriptions. If you have an integration     that uses the Eventbrite API, you may need to have a developer implement     these changes.     What's changing?     The Event object we use currently has both     a summary field and a description field. Both fields currently hold the     same data: A brief summary of an event no longer than 140 characters. We     will be removing the description field from the Event object, and will     instead only accept requests and send responses with the optional summary     field. The benefit of this change is to simplify creating events     through our API and reduce the confusion that comes with having two fields     with the same purpose.     When do these changes     take effect?     Beginning March 1st, 2021 any     API requests which read or write to the 'event.description' field will     return an error. | Hi,     We’re writing to inform you     that we will be making a breaking change to our API related to our Event     object and the way we handle event descriptions. If you have an integration     that uses the Eventbrite API, you may need to have a developer implement     these changes.     What's changing?     The Event object we use currently has both     a summary field and a description field. Both fields currently hold the     same data: A brief summary of an event no longer than 140 characters. We     will be removing the description field from the Event object, and will     instead only accept requests and send responses with the optional summary     field. The benefit of this change is to simplify creating events     through our API and reduce the confusion that comes with having two fields     with the same purpose.     When do these changes     take effect?     Beginning March 1st, 2021 any     API requests which read or write to the 'event.description' field will     return an error.

Refer this email.

**Comment by sourabhagarwal07** [comment]
waiting for March 1st to investigate if any changes are required.

**Comment by HarmanBhutani** [comment]
Eventbrite API working fine
