### ISSUE TITLE
Email needs to enable permissions from gmail time and again.

### ISSUE THREAD

**Issue by navpreetkaur051** [pdc-uottawa/PDCwebsite#53]
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by navpreetkaur051** [comment]
related to issue#58

**Comment by navpreetkaur051** [comment]
Email notifications to project ownere work intermiadiately #58
Similar issue.

**Comment by navpreetkaur051** [comment]
Main task: https://github.com/pdc-uottawa/PDCwebsite/issues/30#issue-741137572

Closed that for now.

**Comment by sourabhagarwal07** [comment]
Made changes to the email template, email delivery system (Using outlook now). currently, the email system uses my credential for delivering email but later will be changed to PDC mail once created in the outlook domain.

**Comment by HarmanBhutani** [comment]
working fine and tested
