### ISSUE TITLE
Https issue on website

### ISSUE THREAD

**Issue by navpreetkaur051** [pdc-uottawa/PDCwebsite#57]

**Comment by navpreetkaur051** [comment]
Verify redirection.
logins through - google, linkedin and outlook.
https on gespdc.com

**Comment by HarmanBhutani** [comment]
https on gespdc.com is done , we can see  https://gespdc.com working

![Screen Shot 2021-02-02 at 7 23 01 PM](https://user-images.githubusercontent.com/11242265/106680145-13fb5f80-658c-11eb-9171-0e5f69d7af00.png)

**Comment by HarmanBhutani** [comment]
issue for not secure even after https has been raised and is getting tracked under heroku ticket:-

https://help.heroku.com/958324

**Comment by HarmanBhutani** [comment]
tested and working fine
